sub-auto=fuzzy
sub-file-paths=sub;subtitles;Subs
sub-font="Roboto"
sub-bold=yes
sub-font-size=32
sub-color="#FFFFFF"
sub-border-size=2
sub-shadow-offset=1

audio-file-auto=fuzzy
alang=jpn,eng,en,ja
slang=eng,en

osc=yes
osd-font="JetBrainsMono Nerd Font"
osd-bold=yes
osd-font-size=32
osd-playing-msg="${media-title}"

save-position-on-quit=yes
keep-open=yes
ytdl=yes
ytdl-format=bestvideo[height<=1080]+bestaudio/best

deband=yes
video-sync=display-resample
